runtime: nodejs14 # or another supported version
service: social-app
instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto


# this file is being used for uploading the app to compute engine