export {default as reducerForAdvertisement } from "./reducer_for_Advertisement.js";
export {default as reducerForBook } from "./reducer_for_Book.js";
export {default as reducerForComment } from "./reducer_for_Comment.js";
export {default as reducerForLike } from "./reducer_for_Like.js";
export {default as reducerForPage } from "./reducer_for_Page.js";
export {default as reducerForShare } from "./reducer_for_Share.js";
export {default as reducerForSocialPost } from "./reducer_for_SocialPost.js";
export {default as reducerForSport } from "./reducer_for_Sport.js";
export {default as reducerForUser } from "./reducer_for_User.js";
